title: Travels with Mally
description: > # this means to ignore newlines until "baseurl:"
  Tales of an American who moved to the south of France during the coronavirus pandemic.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.travelswithmally.com" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Mallory Shaner
author-img: profile.jpg
about-author: I don't have a dog with me or a custom-designed truck, but I do have an insatiable wanderlust and an appreciation for meeting new people and discovering new things.
social-facebook: malloryshaner
social-email: malloryws901@gmail.com
social-instagram: mal_pallin_around_provence

# Disqus
discus-identifier: travels-with-mally-1

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji
  - jekyll-seo-tag
  - jekyll-feed

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
